export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ORDER_DETAILS = "ORDER_DETAILS";
export const REMOVE_ORDER_DETAILS = "REMOVE_ORDER_DETAILS";
export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";
export const RESET_CART = "RESET_CART";