 export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCT_REQUEST"
 export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCT_SUCCESS"
 export const ALL_PRODUCTS_FAIL = "ALL_PRODUCT_FAIL"

 export const ADMIN_PRODUCTS_REQUEST = "ADMIN_PRODUCT_REQUEST"
 export const ADMIN_PRODUCTS_SUCCESS = "ADMIN_PRODUCT_SUCCESS"
 export const ADMIN_PRODUCTS_FAIL = "ADMIN_PRODUCT_FAIL"

 export const CREATE_ADMIN_PRODUCTS_REQUEST = "CREATE_ADMIN_PRODUCTS_REQUEST"
 export const CREATE_ADMIN_PRODUCTS_SUCCESS = "CREATE_ADMIN_PRODUCTS_SUCCESS"
 export const CREATE_ADMIN_PRODUCTS_RESET = "CREATE_ADMIN_PRODUCTS_RESET"
 export const CREATE_ADMIN_PRODUCTS_FAIL = "CREATE_ADMIN_PRODUCTS_FAIL"

 export const DELETE_ADMIN_PRODUCTS_REQUEST = "DELETE_ADMIN_PRODUCTS_REQUEST"
 export const DELETE_ADMIN_PRODUCTS_SUCCESS = "DELETE_ADMIN_PRODUCTS_SUCCESS"
 export const DELETE_ADMIN_PRODUCTS_RESET = "DELETE_ADMIN_PRODUCTS_RESET"
 export const DELETE_ADMIN_PRODUCTS_FAIL = "DELETE_ADMIN_PRODUCTS_FAIL"

 export const UPDATE_ADMIN_PRODUCTS_REQUEST = "UPDATE_ADMIN_PRODUCTS_REQUEST"
 export const UPDATE_ADMIN_PRODUCTS_SUCCESS = "UPDATE_ADMIN_PRODUCTS_SUCCESS"
 export const UPDATE_ADMIN_PRODUCTS_RESET = "UPDATE_ADMIN_PRODUCTS_RESET"
 export const UPDATE_ADMIN_PRODUCTS_FAIL = "UPDATE_ADMIN_PRODUCTS_FAIL"


 export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST"
 export const PRODUCT_DETAILS_SUCCESS = "PRODUCT_DETAILS_SUCCESS"
 export const PRODUCT_DETAILS_FAIL = "PRODUCT_DETAILS_FAIL"

 
 export const NEW_REVIEW_REQUEST = "NEW_REVIEW_REQUEST"
 export const NEW_REVIEW_SUCCESS = "NEW_REVIEW_SUCCESS"
 export const NEW_REVIEW_RESET = "NEW_REVIEW_RESET"
 export const NEW_REVIEW_FAIL = "NEW_REVIEW_FAIL"

 export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST"
 export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS"
 export const DELETE_REVIEW_RESET = "DELETE_REVIEW_RESET"
 export const DELETE_REVIEW_FAIL = "DELETE_REVIEW_FAIL"

 export const ALL_REVIEW_REQUEST = "ALL_REVIEW_REQUEST"
 export const ALL_REVIEW_SUCCESS = "ALL_REVIEW_SUCCESS"
 export const ALL_REVIEW_FAIL = "ALL_REVIEW_FAIL"


 export const CLEAR_ERRORS = "CLEAR_ERRORS"