export const CREATE_VEHICLE_REQUEST = "CREATE_VEHICLE_REQUEST";
export const CREATE_VEHICLE_SUCCESS = "CREATE_VEHICLE_SUCCESS";
export const CREATE_VEHICLE_RESET = "CREATE_VEHICLE_RESET";
export const CREATE_VEHICLE_FAIL = "CREATE_VEHICLE_FAIL";

export const ALL_VEHICLES_REQUEST = "ALL_VEHICLES_REQUEST";
export const ALL_VEHICLES_SUCCESS = "ALL_VEHICLES_SUCCESS";
export const ALL_VEHICLES_FAIL = "ALL_VEHICLES_FAIL";

export const TRANSPORT_VEHICLES_REQUEST = "TRANSPORT_VEHICLES_REQUEST";
export const TRANSPORT_VEHICLES_SUCCESS = "TRANSPORT_VEHICLES_SUCCESS";
export const TRANSPORT_VEHICLES_FAIL = "TRANSPORT_VEHICLES_FAIL";

export const VEHICLE_DETAILS_REQUEST = "VEHICLE_DETAILS_REQUEST";
export const VEHICLE_DETAILS_SUCCESS = "VEHICLE_DETAILS_SUCCESS";
export const VEHICLE_DETAILS_FAIL = "VEHICLE_DETAILS_FAIL";

export const  VEHICLE_REVIEW_REQUEST = "VEHICLE_REVIEW_REQUEST"
 export const VEHICLE_REVIEW_SUCCESS = "VEHICLE_REVIEW_SUCCESS"
 export const VEHICLE_REVIEW_RESET = "VEHICLE_REVIEW_RESET"
 export const VEHICLE_REVIEW_FAIL = "VEHICLE_REVIEW_FAIL"

 export const TRANSPORTAGENCY_VEHICLE_REQUEST = "TRANSPORTAGENCY_VEHICLE_REQUEST"
 export const TRANSPORTAGENCY_VEHICLE_SUCCESS = "TRANSPORTAGENCY_VEHICLE_SUCCESS"
 export const TRANSPORTAGENCY_VEHICLE_FAIL = "TRANSPORTAGENCY_VEHICLE_FAIL"

 export const DELETE_TRANSPORTAGENCY_VEHICLE_REQUEST = "DELETE_TRANSPORTAGENCY_VEHICLE_REQUEST"
 export const DELETE_TRANSPORTAGENCY_VEHICLE_SUCCESS = "DELETE_TRANSPORTAGENCY_VEHICLE_SUCCESS"
 export const DELETE_TRANSPORTAGENCY_VEHICLE_RESET = "DELETE_TRANSPORTAGENCY_VEHICLE_RESET"
 export const DELETE_TRANSPORTAGENCY_VEHICLE_FAIL = "DELETE_TRANSPORTAGENCY_VEHICLE_FAIL"

 export const UPDATE_TRANSPORTAGENCY_VEHICLE_REQUEST = "UPDATE_TRANSPORTAGENCY_VEHICLE_REQUEST"
 export const UPDATE_TRANSPORTAGENCY_VEHICLE_SUCCESS = "UPDATE_TRANSPORTAGENCY_VEHICLE_SUCCESS"
 export const UPDATE_TRANSPORTAGENCY_VEHICLE_RESET = "UPDATE_TRANSPORTAGENCY_VEHICLE_RESET"
 export const UPDATE_TRANSPORTAGENCY_VEHICLE_FAIL = "UPDATE_TRANSPORTAGENCY_VEHICLE_FAIL"

 export const ALL_VEHICLE_REVIEW_REQUEST = "ALL_VEHICLE_REVIEW_REQUEST"
 export const ALL_VEHICLE_REVIEW_SUCCESS = "ALL_VEHICLE_REVIEW_SUCCESS"
 export const ALL_VEHICLE_REVIEW_FAIL = "ALL_VEHICLE_REVIEW_FAIL"

 export const DELETE_VEHICLE_REVIEW_REQUEST = "DELETE_VEHICLE_REVIEW_REQUEST"
 export const DELETE_VEHICLE_REVIEW_SUCCESS = "DELETE_VEHICLE_REVIEW_SUCCESS"
 export const DELETE_VEHICLE_REVIEW_RESET = "DELETE_VEHICLE_REVIEW_RESET"
 export const DELETE_VEHICLE_REVIEW_FAIL = "DELETE_VEHICLE_REVIEW_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";
